get:
  responses:
    '200':
      content:
        application/json:
          schema:
            properties:
              auto_post:
                type: integer
              cash:
                type: integer
              comps:
                type: integer
              department:
                type: integer
              discount_type:
                type: integer
              document_email_username:
                type: string
              doe_detailed:
                type: integer
              frequency:
                type: integer
              guest_count:
                type: integer
              has_fixed_conditions:
                type: integer
              indirect_labor:
                type: integer
              inventory:
                type: integer
              labor:
                type: integer
              labor_calculator:
                type: integer
              operating_expense:
                type: integer
              show_hours:
                type: integer
            type: object
      description: OK
    '401':
      content:
        application/json:
          schema:
            properties:
              message:
                example: Unauthenticated.
                type: string
            type: object
      description: Unauthorized
  security:
    - bearerAuth: []
  tags:
    - settings
