openapi: 3.0.0
info:
  title: clickBACON API
  version: 1.0.0
  description: API documentation for clickBACON.
  x-logo:
    url: https://app.clickbacon.com/images/bacon-logo.png
servers:
  - url: https://alpha.clickbacon.com/api
    description: Alpha server
  - url: http://localhost:8000/api
    description: Development server
paths:
  /setup:
    $ref: paths/setup.yaml
  /header:
    $ref: paths/header.yaml
  /sidebar:
    $ref: paths/sidebar.yaml
  /new-feature/status:
    $ref: paths/new-feature_status.yaml
  /date-filter:
    $ref: paths/date-filter.yaml
  /push/count:
    $ref: paths/push_count.yaml
  /dashboard/settings:
    $ref: paths/dashboard_settings.yaml
  /user/hide-previous-banner:
    $ref: paths/user_hide-previous-banner.yaml
  /dashboard/health:
    $ref: paths/dashboard_health.yaml
  /settings/transactions:
    $ref: paths/settings_transactions.yaml
  /dashboard/cogs:
    $ref: paths/dashboard_cogs.yaml
  /dashboard/accounts:
    $ref: paths/dashboard_accounts.yaml
  /dashboard/primecost:
    $ref: paths/dashboard_primecost.yaml
  /dashboard/comps:
    $ref: paths/dashboard_comps.yaml
  /dashboard/doe:
    $ref: paths/dashboard_doe.yaml
  /dashboard/labor:
    $ref: paths/dashboard_labor.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
